# Generated by Django 5.1.7 on 2025-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_id', models.IntegerField()),
                ('gas_resistance', models.FloatField()),
                ('humidity', models.FloatField()),
                ('lux', models.FloatField()),
                ('pressure', models.FloatField()),
                ('rawVal', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('volts', models.FloatField()),
            ],
        ),
    ]
